#!/usr/bin/env python3
"""Check the hazard -> requirement -> module -> contract -> test chain.

Trace tables written in prose are intentions: a renamed test, a deleted requirement, or
a mitigation pointing at nothing stays invisible until it matters. This makes them
checkable.

No dependencies. The trace format is a deliberately restricted YAML subset -- a list of
records with scalar and inline-list values -- so it parses with stdlib alone and stays
readable to a reviewer who does not read code.

Usage:
    python tooling/check_traces.py                  # CI: exit 1 on any break
    python tooling/check_traces.py --strict         # also fail on unplanned requirements
    python tooling/check_traces.py --report         # emit the review matrix as markdown
    python tooling/check_traces.py --trace-dir DIR  # default: trace/

Expected files (see CORE-TRC-001):
    trace/requirements.yaml   id, statement, allocated_to, verified_by[], source
    trace/hazards.yaml        id, never_statement, severity, mitigation_*, requirement
    trace/slices.yaml         id, name, requirements[], hazards[], status
    trace/tests.txt           one test id per line, GENERATED by test collection
"""

import sys
from pathlib import Path

VALID_MITIGATION_STATUS = {"proposed", "traced", "verified"}


# --------------------------------------------------------------------------- parsing

def parse_records(text, path):
    """Parse a flat list of records. Supports:

        - key: value
          other: [a, b, c]
          # comment

    Deliberately not general YAML. Nested structures are rejected loudly rather than
    silently mis-parsed, because a silently mis-parsed trace is worse than no trace.
    """
    records, current, errors = [], None, []

    for lineno, raw in enumerate(text.splitlines(), 1):
        line = raw.rstrip()
        if not line.strip() or line.lstrip().startswith("#"):
            continue

        stripped = line.lstrip()
        indent = len(line) - len(stripped)

        if stripped.startswith("- "):
            current = {}
            records.append(current)
            stripped = stripped[2:].strip()
            if not stripped:
                continue
        elif current is None:
            errors.append(f"{path}:{lineno}: content before the first '- ' record")
            continue
        elif indent == 0:
            errors.append(f"{path}:{lineno}: unindented line inside a record")
            continue

        if ":" not in stripped:
            errors.append(f"{path}:{lineno}: expected 'key: value', got {stripped!r}")
            continue

        key, _, val = stripped.partition(":")
        key, val = key.strip(), val.strip()

        if not val:
            errors.append(
                f"{path}:{lineno}: '{key}' has no value "
                "(nested structures are not supported; keep records flat)"
            )
            continue

        if val.startswith("[") and val.endswith("]"):
            inner = val[1:-1].strip()
            current[key] = [v.strip().strip("\"'") for v in inner.split(",") if v.strip()]
        else:
            current[key] = val.strip("\"'")

    return records, errors


def load(trace_dir, name, required_fields, errors):
    path = trace_dir / name
    if not path.exists():
        errors.append(f"missing {path}")
        return []

    records, perrors = parse_records(path.read_text(encoding="utf-8"), path)
    errors.extend(perrors)

    seen = {}
    for i, r in enumerate(records, 1):
        rid = r.get("id")
        if not rid:
            errors.append(f"{path}: record {i} has no id")
            continue
        if rid in seen:
            errors.append(f"{path}: duplicate id {rid}")
        seen[rid] = r
        for f in required_fields:
            if f not in r:
                errors.append(f"{path}: {rid} missing required field '{f}'")

    return records


def load_tests(trace_dir, errors):
    path = trace_dir / "tests.txt"
    if not path.exists():
        errors.append(
            f"missing {path} -- generate it from test collection immediately before "
            "this check; a hand-maintained manifest defeats the mechanism"
        )
        return None
    ids = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            ids.add(line)
            # Also index the bare test name so traces need not carry full paths.
            ids.add(line.rsplit("::", 1)[-1])
    return ids


# --------------------------------------------------------------------------- checks

def check(reqs, hazards, slices, tests, strict):
    errors, warnings = [], []
    req_ids = {r["id"] for r in reqs if "id" in r}
    hz_ids = {h["id"] for h in hazards if "id" in h}

    def test_exists(name):
        return tests is None or name in tests

    for r in reqs:
        rid = r.get("id")
        if not rid:
            continue

        if not r.get("allocated_to"):
            errors.append(f"{rid}: not allocated to a module -- an orphan requirement "
                          "is nobody's job")

        verified = r.get("verified_by") or []
        if isinstance(verified, str):
            verified = [verified]
        if not verified:
            errors.append(f"{rid}: no verifying test")
        for t in verified:
            if t != "TBD" and not test_exists(t):
                errors.append(f"{rid}: verified_by names '{t}', which is not in tests.txt "
                              "(renamed or deleted?)")
            if t == "TBD":
                warnings.append(f"{rid}: verification is TBD")

        src = r.get("source")
        if src and src not in hz_ids and not src.startswith(("STK", "ASM", "GOAL")):
            errors.append(f"{rid}: source '{src}' does not resolve to a known hazard")

    for h in hazards:
        hid = h.get("id")
        if not hid:
            continue

        status = h.get("mitigation_status", "")
        if status not in VALID_MITIGATION_STATUS:
            errors.append(f"{hid}: mitigation_status '{status}' invalid "
                          f"(expected one of {sorted(VALID_MITIGATION_STATUS)})")

        if not h.get("mitigation_contract"):
            errors.append(f"{hid}: no mitigation_contract -- a mitigation with no control "
                          "is a statement of intent")

        mtest = h.get("mitigation_test", "")
        if not mtest:
            errors.append(f"{hid}: no mitigation_test")
        elif mtest == "TBD":
            if status != "proposed":
                errors.append(f"{hid}: mitigation_test is TBD but status is '{status}' -- "
                              "TBD is permitted only while proposed")
            else:
                warnings.append(f"{hid}: mitigation test TBD (must be resolved by G3)")
        elif not test_exists(mtest):
            errors.append(f"{hid}: mitigation_test '{mtest}' is not in tests.txt")
        elif status == "verified" and tests is not None and mtest not in tests:
            errors.append(f"{hid}: claims verified but its test does not exist")

        req = h.get("requirement")
        if req and req not in req_ids:
            errors.append(f"{hid}: requirement '{req}' does not resolve")

        if not h.get("never_statement"):
            warnings.append(f"{hid}: no never_statement -- the G0 reviewer needs one")

    planned = set()
    for s in slices:
        sid = s.get("id", "?")
        for rid in s.get("requirements", []):
            planned.add(rid)
            if rid not in req_ids:
                errors.append(f"{sid}: claims requirement '{rid}', which does not exist")
        for hid in s.get("hazards", []):
            if hid not in hz_ids:
                errors.append(f"{sid}: claims hazard '{hid}', which does not exist")

    for rid in sorted(req_ids - planned):
        msg = f"{rid}: not claimed by any slice"
        (errors if strict else warnings).append(msg)

    return errors, warnings


# --------------------------------------------------------------------------- report

def report(reqs, hazards, slices, tests):
    def mark(ok):
        return "yes" if ok else "**NO**"

    def exists(t):
        return tests is None or t in tests

    out = ["# Trace Matrix", "",
           "Generated by `tooling/check_traces.py --report`. Review artifact for gates "
           "G1-G3 and slice acceptance; readable without reading code.", "",
           "## Requirements", "",
           "| Requirement | Module | Verified by | Tests exist | Source |",
           "|---|---|---|---|---|"]

    for r in sorted(reqs, key=lambda x: x.get("id", "")):
        v = r.get("verified_by") or []
        if isinstance(v, str):
            v = [v]
        out.append(
            f"| `{r.get('id','?')}` {r.get('statement','')} "
            f"| {r.get('allocated_to','-')} "
            f"| {', '.join(v) if v else '-'} "
            f"| {mark(bool(v) and all(t != 'TBD' and exists(t) for t in v))} "
            f"| {r.get('source','-')} |"
        )

    out += ["", "## Hazards", "",
            "| Hazard | Must never happen | Severity | Control | Test | Status |",
            "|---|---|---|---|---|---|"]

    for h in sorted(hazards, key=lambda x: x.get("id", "")):
        mt = h.get("mitigation_test", "-")
        ok = mt not in ("-", "TBD") and exists(mt)
        out.append(
            f"| `{h.get('id','?')}` | {h.get('never_statement','-')} "
            f"| {h.get('severity','-')} | {h.get('mitigation_contract','-')} "
            f"| {mt} {'' if ok else '(missing)'} | {h.get('mitigation_status','-')} |"
        )

    out += ["", "## Slices", "", "| Slice | Requirements | Hazards | Status |",
            "|---|---|---|---|"]
    for s in sorted(slices, key=lambda x: x.get("id", "")):
        out.append(
            f"| `{s.get('id','?')}` {s.get('name','')} "
            f"| {', '.join(s.get('requirements', [])) or '-'} "
            f"| {', '.join(s.get('hazards', [])) or '-'} "
            f"| {s.get('status','-')} |"
        )

    unverified = [h.get("id") for h in hazards if h.get("mitigation_status") != "verified"]
    out += ["", "## Open items", ""]
    out.append(f"- Hazards not yet verified: {', '.join(unverified) if unverified else 'none'}")
    out.append(f"- Requirements: {len(reqs)} · Hazards: {len(hazards)} · Slices: {len(slices)}")

    return "\n".join(out) + "\n"


# --------------------------------------------------------------------------- main

def main():
    args = sys.argv[1:]
    strict = "--strict" in args
    do_report = "--report" in args

    trace_dir = Path("trace")
    if "--trace-dir" in args:
        trace_dir = Path(args[args.index("--trace-dir") + 1])

    load_errors = []
    reqs = load(trace_dir, "requirements.yaml",
                ["statement", "allocated_to", "verified_by"], load_errors)
    hazards = load(trace_dir, "hazards.yaml",
                   ["severity", "mitigation_contract", "mitigation_test",
                    "mitigation_status"], load_errors)
    slices = load(trace_dir, "slices.yaml", ["name"], load_errors)
    tests = load_tests(trace_dir, load_errors)

    fatal = [e for e in load_errors if e.startswith("missing ")]
    if fatal:
        for e in fatal:
            print(f"ERROR {e}", file=sys.stderr)
        return 1

    errors, warnings = check(reqs, hazards, slices, tests, strict)
    errors = load_errors + errors

    if do_report:
        print(report(reqs, hazards, slices, tests))
        return 0

    for w in warnings:
        print(f"WARN  {w}", file=sys.stderr)
    for e in errors:
        print(f"ERROR {e}", file=sys.stderr)

    if errors:
        print(f"\n{len(errors)} trace break(s). Traces are updated in the session that "
              "changes the thing being traced.", file=sys.stderr)
        return 1

    print(f"OK {len(reqs)} requirements, {len(hazards)} hazards, {len(slices)} slices; "
          f"chain intact ({len(warnings)} warning(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
