#!/usr/bin/env python3
"""Flag imperatives that have drifted from their source sections or their carrier.

CLAUDE.md carries imperatives; core carries the rules they derive from. The two drift
silently: a section changes in core and the imperative keeps the old wording, or someone
edits the rendered table by hand. Three failure modes (CORE-IMP-001):

    source section changed     re-read the section, fix the fragment or confirm, --accept
    table differs from map     the carrying CLAUDE.md was edited by hand; regenerate
    one side only              a map row with no table row, or the reverse; regenerate

This does not prove an imperative is still correct. It forces someone to look.

Usage:
    python tooling/check_imperatives.py                 # CI: exit 1 on any failure
    python tooling/check_imperatives.py --accept        # re-record hashes after confirming
    python tooling/check_imperatives.py --root DIR      # a project root (default: cwd)

Run from a project, or with --root, it reads the project's .hyperion/imperatives.json
and compares it with the project's CLAUDE.md, hashing the vendored framework this script
belongs to. --accept is refused there: that map is generated by init_project.py, and a
drift means the vendored framework moved on, so the fix is init_project.py --upgrade.
"""

import argparse
import json
import sys
from pathlib import Path

import framework_docs as fd

FRAMEWORK_MAP = fd.FRAMEWORK_ROOT / "tooling" / "imperatives.json"


def locate(root_arg):
    """(map path, carrier base directory, is_project)."""
    root = Path(root_arg or Path.cwd()).resolve()
    project_map = root / ".hyperion" / "imperatives.json"
    if project_map.exists():
        return project_map, root, True
    if root_arg:
        raise SystemExit(f"ERROR {root}: no .hyperion/imperatives.json; run init_project.py first")
    return FRAMEWORK_MAP, fd.FRAMEWORK_ROOT, False


def check_sources(data, by_id, accept):
    """Failure mode 1: the source section's hash differs from the recorded one."""
    drift, missing = [], []
    for imp in data["imperatives"]:
        try:
            _, _, body = fd.resolve_source(by_id, imp["source"])
        except ValueError as e:
            missing.append(f"{imp['id']}: {e}")
            continue
        current = fd.section_hash(body)
        if current != imp["section_hash"]:
            drift.append(imp)
            if accept:
                imp["section_hash"] = current
    return drift, missing


def check_carriers(data, base):
    """Failure modes 2 and 3: every carrier with a rendered table matches the map."""
    errors = []
    by_carrier = {}
    for imp in data["imperatives"]:
        by_carrier.setdefault(imp["carried_in"], {})[imp["id"]] = imp
    for carrier, rows in by_carrier.items():
        path = base / carrier
        if not path.exists():
            errors.append(f"{carrier}: carrier file missing")
            continue
        table = fd.parse_imperative_table(fd.read(path))
        if table is None:
            continue        # a fragment or a prose carrier: nothing rendered to compare
        for iid in sorted(set(rows) - set(table)):
            errors.append(f"{iid}: in the map but not in {carrier}")
        for iid in sorted(set(table) - set(rows)):
            errors.append(f"{iid}: in {carrier} but not in the map")
        for iid in sorted(set(rows) & set(table)):
            text, source = table[iid]
            if text != rows[iid]["text"] or source != rows[iid]["source"]:
                errors.append(f"{iid}: {carrier} differs from the map (edited by hand?)")
    return errors


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--accept", action="store_true")
    ap.add_argument("--root", help="project root (default: cwd if it has .hyperion/, else framework)")
    args = ap.parse_args(argv)

    map_path, base, is_project = locate(args.root)
    if not map_path.exists():
        print(f"ERROR missing {map_path}; run build_layer.py", file=sys.stderr)
        return 1
    if args.accept and is_project:
        print("ERROR --accept is refused in a project: the map is generated. "
              "Run init_project.py --upgrade after re-reading what changed.", file=sys.stderr)
        return 1

    data = json.loads(map_path.read_text(encoding="utf-8"))
    by_id = fd.docs_by_id(fd.collect_docs(fd.FRAMEWORK_ROOT))
    drift, missing = check_sources(data, by_id, args.accept)
    carrier_errors = check_carriers(data, base)

    for m in missing:
        print(f"ERROR {m}", file=sys.stderr)
    for e in carrier_errors:
        print(f"ERROR {e}", file=sys.stderr)

    if args.accept:
        map_path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
        print(f"Re-recorded {len(drift)} section hash(es)")
        return 1 if (missing or carrier_errors) else 0

    if drift:
        print("Source sections changed since these imperatives were last confirmed:\n", file=sys.stderr)
        for imp in drift:
            print(f"  {imp['id']}  [{imp['source']}]  in {imp['carried_in']}", file=sys.stderr)
            print(f"      \"{imp['text']}\"", file=sys.stderr)
            fix = "init_project.py --upgrade" if is_project else "--accept"
            print(f"      re-read {imp['source_path']}#{imp['source'].split('#')[1]}, then {fix}\n",
                  file=sys.stderr)

    if drift or missing or carrier_errors:
        return 1
    where = "project map" if is_project else "framework map"
    print(f"OK {len(data['imperatives'])} imperatives ({where}): sources unchanged, carriers match")
    return 0


if __name__ == "__main__":
    sys.exit(main())
