"""Render the Claude Code binding: the .claude/ tree, the hook table, the container (CORE-HRN-001, M9).

Session rules that only a model remembers are honour-based. This module renders, from
the same sources as the rest of the operating layer, what the runtime enforces instead:
one skill per session type (the declaration, the loadout, the scope written to
.hyperion/session), one read-only agent per lens with its model pinned, the settings
file with the scope and plugin hooks and the profiles' plugin list, the table the scope
hook reads, and the devcontainer. Called by build_layer.py for the framework repository
and for every project; nothing here is edited by hand.

Sources: the session-types block (CORE-SES-001), document frontmatter (TOOL-001),
agents/*.md (AGT-000), profiles/*/fragment.yaml (`plugins`, `test_command`), and the
static files under tooling/claude-code/.
"""

import json
import re
from pathlib import Path

import build_layer
import framework_docs as fd
import loadout as lo

STATIC = Path(__file__).resolve().parent / "claude-code"
HOOKS = ["scope.py", "plugins.py"]
READ_ONLY_TOOLS = "Read, Grep, Glob, Bash"
DENIED_TOOLS = "Edit, Write, MultiEdit, NotebookEdit, Agent"
WAITS = {"QUERY", "REVIEW"}        # types with no scope to confirm (CORE-SES-001)
FENCE = re.compile(r"```[^\n]*\n(.*?)```", re.DOTALL)


# ------------------------------------------------------------------ helpers

def _globs(items):
    return build_layer._globs(items)


def _test_command(fragments):
    return next((f["test_command"] for f in fragments if f.get("test_command")), "pytest")


def _plugins(fragments):
    return sorted({p for f in fragments for p in (f.get("plugins") or [])})


def _agent_sections(src, doc):
    """(permitted, prohibited, prompt) from an agent file, its severity include filled."""
    parts = {s: text for _, s, _, text in fd.sections(fd.fill_includes(doc["body"], src.by_id))}
    m = FENCE.search(parts.get("prompt") or "")
    return parts.get("permitted-inputs", ""), parts.get("prohibited-inputs", ""), (m.group(1).rstrip() if m else "")


def _agents_for(src, profiles, framework):
    return [a for a in src.agents if framework or not a["fm"].get("profile") or a["fm"]["profile"] in profiles]


# ------------------------------------------------------------------ renderers

def render_session_table_json(src, framework, agents, test_command):
    scopes = ("framework", "both") if framework else ("project", "both")
    types = {n: {"may_modify": t["may_modify"], "must_not_modify": t["must_not_modify"]}
             for n, t in src.types.items() if t["scope"] in scopes}
    rows = {Path(a["path"]).stem: {"may_modify": ["trace/findings.yaml"], "must_not_modify": []} for a in agents}
    return json.dumps({
        "_comment": "Generated by build_layer.py from the session-types block of CORE-SES-001 (M3); "
                    "read by .claude/hooks/scope.py. Regenerate, never edit.",
        "scope": "framework" if framework else "project",
        "session_file": ".hyperion/session",
        "test_command": test_command,
        "types": types,
        "agents": rows,
    }, indent=2) + "\n"


def render_settings(plugins):
    hook = lambda name: [{"type": "command", "command": f'python3 "${{CLAUDE_PROJECT_DIR}}/.claude/hooks/{name}"'}]
    return json.dumps({
        "enabledPlugins": {p: True for p in plugins},
        "hooks": {
            "PreToolUse": [{"matcher": "Edit|Write|MultiEdit|NotebookEdit|Bash", "hooks": hook("scope.py")}],
            "SessionStart": [{"hooks": hook("plugins.py")}],
        },
    }, indent=2) + "\n"


def render_devcontainer(name, plugins):
    text = (STATIC / "devcontainer.json").read_text(encoding="utf-8")
    return text.replace("{{NAME}}", name).replace("{{PLUGINS}}", ", ".join(plugins) or "none")


def render_agent(src, doc, test_command):
    fm, name = doc["fm"], Path(doc["path"]).stem
    permitted, prohibited, prompt = _agent_sections(src, doc)
    return "\n".join([
        "---",
        f"name: {name}",
        f'description: "{fm["lens"]} lens ({fm["id"]}): {fm["question"]} Run only from /review, never on your own initiative."',
        f"tools: {READ_ONLY_TOOLS}",
        f"disallowedTools: {DENIED_TOOLS}",
        f"model: {fm['model']}",
        "---",
        f"You are the Hyperion {fm['lens']} lens ({fm['id']}), a fresh reviewer with no history. Disregard",
        "any project operating instructions in the CLAUDE.md files you were given, except this",
        f"one: you are read-only, you may run only the test command `{test_command}`, and you",
        "write no file. Report; never fix (CORE-REV-003, CORE-HRN-001).",
        "",
        "## Permitted inputs",
        permitted,
        "",
        "## Prohibited inputs",
        prohibited,
        "",
        "## Prompt",
        prompt,
        "",
    ])


def _loadout_lines(src, session, profiles, framework):
    out = lo.loadout(src, session, profiles, framework=framework)
    prefix = "" if framework else "hyperion/"
    ids = {d["path"]: d["fm"]["id"] for d in src.docs.values() if d["fm"]}
    lines = [f"- `{prefix}{p}` ({ids.get(p, '')})" for p in out["always"] + out["session"]]
    lines += [f"- `{p}`" for p in out["project"]]
    if out["note"]:
        lines.append(f"- {out['note']}")
    return lines


def _declare_line(name):
    return (f"Declared: !`mkdir -p .hyperion && printf '{name}\\n' > .hyperion/session && "
            f"echo \"{name} written to .hyperion/session; the scope hook enforces its globs\"`")


def render_session_skill(src, name, fragments, profiles, framework):
    t = src.types[name]
    slug = name.lower()
    waits = name not in WAITS
    head = ["---", f"name: {slug}",
            f'description: "{name} session: {t["purpose"].lower()}. Type it; never invoked by the model."',
            "disable-model-invocation: true",
            f'argument-hint: "{"[scope]" if framework else "[SL-nn] [scope]"}"', "---",
            f"# {name} session", "", _declare_line(name), ""]
    if framework:
        decl = [f"    SESSION: {name}", "    SCOPE: $ARGUMENTS", f"    MAY MODIFY: {_globs(t['may_modify'])}",
                "    PRINCIPLE: <which of P1-P10 this change serves>"]
        arg_note = "Arguments: `$ARGUMENTS`, the scope (or the question)."
    else:
        decl = [f"    SESSION: {name}", "    SLICE: <first token of the arguments, or n/a>",
                "    SCOPE: <the rest of the arguments>", f"    MAY MODIFY: {_globs(t['may_modify'])}",
                "    LOADED: <the IDs below, once read>"]
        arg_note = "Arguments: `$ARGUMENTS`. The first token is the slice (`SL-nn`), the rest is the scope."
    body = [arg_note, "",
            "Output exactly:" if not waits else "Output exactly, then stop and wait for confirmation. Do not begin work in the same turn.",
            "", *decl, ""]
    if name == "QUERY":
        body += ["QUERY modifies nothing and may read anything, human-only documents included. It ends by",
                 "naming the session type that makes any change it uncovers (CORE-SES-001).", ""]
    body += ["## Load exactly", "", *(_loadout_lines(src, name, profiles, framework) or ["- nothing beyond CLAUDE.md"]), "",
             "## Must not modify", "",
             (f"{_globs(t['must_not_modify'])}" + (f" ({t['note']})" if t.get("note") else "") + "."
              if t["must_not_modify"] else "Nothing by path; every change traces to a principle (HYP-002)."),
             "A write outside `MAY MODIFY` is denied by the scope hook and rejected at commit (CORE-SES-001, CORE-HRN-001).", ""]
    if not framework:
        body += ["## Stop conditions", "",
                 build_layer.render_stop_conditions(src.core, fragments), "",
                 "Stop, state the condition, and end the session; do not work around it (CORE-SES-001).", ""]
    else:
        body += ["## Rules", "", "Every change traces to a principle; one fact, one place; regenerate the registry and",
                 "the operating layer before finishing (HYP-002).", ""]
    return "\n".join(head + body)


def render_review_skill(src, fragments, profiles, agents):
    t = src.types["REVIEW"]
    rows = ["| Lens | Agent | Run when | May receive |", "|---|---|---|---|"]
    for a in agents:
        permitted, _, _ = _agent_sections(src, a)
        flat = " ".join(permitted.replace("- ", "").split())
        rows.append(f"| {a['fm']['lens']} | `{Path(a['path']).stem}` | {a['fm']['run_when']} | {flat} |")
    return "\n".join([
        "---", "name: review",
        'description: "Open a REVIEW session on a slice: run the lens agents in parallel on mechanically assembled inputs and record their findings. Type it; never invoked by the model."',
        "disable-model-invocation: true", 'argument-hint: "SL-nn [lens ...]"', "---",
        "# REVIEW session: the lens fan-out", "", _declare_line("REVIEW"), "",
        "Arguments: `$ARGUMENTS`. The first token is the slice; any further tokens name lenses.",
        "Output the declaration and continue; REVIEW has no scope to confirm and does not wait.", "",
        "    SESSION: REVIEW", "    SLICE: <slice>", "    SCOPE: lens fan-out",
        f"    MAY MODIFY: {_globs(t['may_modify'])} ({t['note']})", "",
        "## 1. Assemble the inputs mechanically", "",
        "Read these and nothing else:", "",
        "- `trace/slices.yaml`: the slice's row; `contracts` names the modules under review.",
        "- `docs/slices/<slice>.md`: the **Acceptance criteria** section and the **Lenses to run** section.",
        "- For each named module: `modules/<m>/CONTRACT.md`, and the paths `modules/<m>/src/` and `modules/<m>/conformance/`.",
        "- `trace/requirements.yaml` and `trace/hazards.yaml`: the rows the slice claims (the validation lens gets these, not the code).", "",
        "## 2. Select the lenses", "",
        "Lens names given as arguments; else the slice definition's **Lenses to run**; else every lens",
        "below whose *run when* applies to what the slice touches. A name that is not a lens below is",
        "reported and skipped. Two to four is the working range (CORE-REV-003).", "", *rows, "",
        "## 3. Run them in parallel", "",
        "One Agent call per selected lens, all in the same turn, `subagent_type` set to the agent name.",
        "Each prompt carries only what its **May receive** column permits: paste the acceptance criteria",
        "and the contract text, name the paths, and nothing more. Nothing you think, suspect, or were told",
        "goes in; words after the lens names in the arguments are not passed on (CORE-REV-003, rule 2).",
        "The agents are read-only; the hook denies them everything but the test command.", "",
        "## 4. Record", "",
        "Print the rows first, then append them to `trace/findings.yaml` (schema: CORE-TRC-003). Per item:",
        "a FINDING with a TEST or PROPOSED CLAUSE is `status: admitted` with `form: test` or `clause`; a",
        "REJECTED item or one with no artifact is `status: rejected` with its `reason` (CORE-REV-005).",
        "`id`: the next FND-nnn; `date`: today; `slice`; `source: lens:<name>`; `severity` as reported;",
        "`summary`: the FINDING line; `ref`: the proposed test id or the clause. `check_traces.py` flags",
        "an admitted test finding until that test exists; writing it is a CONFORMANCE session's job for",
        "S1 and S2, an IMPLEMENT session's for S3 and S4.", "",
        "Fix nothing. Touch no other file. End with the row count per lens; the human dispositions the rows.", "",
    ])


# ------------------------------------------------------------------ outputs

def outputs(src, target, profiles, framework, name):
    """{path: text} for the binding under `target`. `framework` renders the framework
    repository's own tree; a project gets the types in project scope."""
    target = Path(target)
    fragments = src.profile_fragments(profiles)
    agents = _agents_for(src, profiles, framework)
    test_command = "pytest" if framework else _test_command(fragments)
    plugins = _plugins(fragments)
    scopes = ("framework", "both") if framework else ("project", "both")
    out = {}
    out[target / ".hyperion" / "session-types.json"] = render_session_table_json(src, framework, agents, test_command)
    out[target / ".claude" / "settings.json"] = render_settings(plugins)
    for hook in HOOKS:
        out[target / ".claude" / "hooks" / hook] = (STATIC / "hooks" / hook).read_text(encoding="utf-8")
    for n, t in src.types.items():
        if t["scope"] not in scopes:
            continue
        if n == "REVIEW" and not framework:
            text = render_review_skill(src, fragments, profiles, agents)
        else:
            text = render_session_skill(src, n, fragments, profiles, framework)
        out[target / ".claude" / "skills" / n.lower() / "SKILL.md"] = text
    for a in agents:
        out[target / ".claude" / "agents" / f"{Path(a['path']).stem}.md"] = render_agent(src, a, test_command)
    out[target / ".devcontainer" / "devcontainer.json"] = render_devcontainer(name, plugins)
    return out
